version: '3.8'

services:
  nextjs-frontend:
    build:
      context: .
      dockerfile: Dockerfile.next
    container_name: nextjs-proxy
    ports:
      - "3000:3000"
    environment:
      - PYTHON_BACKEND_URL=http://python-backend:5328
    restart: always
    depends_on:
      - python-backend

  python-backend:
    build:
      context: .
      dockerfile: Dockerfile.hidden
    container_name: python-backend
    expose:
      - "5328"
    restart: always