name: CI/CD Push to Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: production-deployment
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying App to LunaNode VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/nextjs-ai-chatbot
            
            git pull origin main

            cat << 'EOF' > .env
            POSTGRES_URL=${{ secrets.POSTGRES_URL }}
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            AUTH_URL=${{ secrets.AUTH_URL }}
            BLOB_READ_WRITE_TOKEN=${{ secrets.BLOB_READ_WRITE_TOKEN }}
            GOOGLE_GENERATIVE_AI_API_KEY=${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            XAI_API_KEY=${{ secrets.XAI_API_KEY }}
            XAI_FREE_KEY_1=${{ secrets.XAI_FREE_KEY_1 }}
            XAI_FREE_KEY_2=${{ secrets.XAI_FREE_KEY_2 }}
            XAI_FREE_KEY_3=${{ secrets.XAI_FREE_KEY_3 }}
            MEM0_API_KEY=${{ secrets.MEM0_API_KEY }}
            FLASK_APP=${{ secrets.FLASK_APP }}
            REDIS_URL=${{ secrets.REDIS_URL }}
            HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
            EOF
            
            sudo docker compose up -d --build
            
            sudo docker image prune -f